# Generated by Django 5.0.4 on 2024-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('flavour', models.TextField(max_length=200)),
                ('topings', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=250)),
                ('phno', models.TextField(max_length=20)),
                ('time', models.TextField(max_length=50)),
                ('quantity', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
